services: 
  db:
    image: postgres:15
    expose:
      - "5432"
    ports:
     - "5432:5432"
    volumes: 
     - ./data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${USER_DB}
      
  api: 
    command: ["node", "index.js"]
    build: 
      context: backend
    expose:
      - "5000"
    ports: 
      - "5000:5000"
    volumes: 
      - ./backend:/app
    

  